require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  TargetRailsVersion: 6.0.3.4
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
