require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  TargetRailsVersion: 6.0.3.4
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Rails:
  Enabled: true

Rails/Validation:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
