version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid
      && bundle exec puma -C config/puma.rb"
    tty: true
    stdin_open: true
    volumes:
      - .:/sparkle
      - public-data:/sparkle/public
      - tmp-data:/sparkle/tmp
      - log-data:/sparkle/log
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - public-data:/sparkle/public
      - tmp-data:/sparkle/tmp
    depends_on:
      - api

  frontend:
    build: ./frontend
    command: sh -c "yarn start"
    tty: true
    stdin_open: true
    ports:
      - "8000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - nginx

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
